# Generated by Django 4.0.2 on 2022-02-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('fabric_types_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('fabric_types', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('colors', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='imageadmin',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            bases=('shop.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_type',
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_types_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='fabric type'),
        ),
    ]
