# Generated by Django 4.0.2 on 2022-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categories_color_imageadmin_remove_product_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
