# Generated by Django 4.0.2 on 2022-03-09 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_contact_us_customerdetails_delete_contactus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='pswd',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Cart_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Wishlist_id',
            field=models.IntegerField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='c_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customerdetails', verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
