# Generated by Django 4.0.2 on 2022-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_customerdetails_pswd_remove_wishlist_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='fname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
