# Generated by Django 4.0.2 on 2022-03-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_customerdetails_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fname', models.CharField(blank=True, max_length=25)),
                ('lname', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('Cart_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(max_length=10)),
                ('Total_Bill', models.IntegerField(max_length=10)),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='c_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
        migrations.AlterField(
            model_name='orders',
            name='Cart_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shoppingcart', verbose_name='cart_id'),
        ),
        migrations.DeleteModel(
            name='Shopping_Cart',
        ),
    ]
