# Generated by Django 4.0.2 on 2022-03-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_details_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='c_id',
            field=models.IntegerField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='c_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customer_details', verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='c_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customer_details', verbose_name='customer_id'),
        ),
    ]
