# Generated by Django 4.0.2 on 2022-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_customer_details_id_remove_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='Cart_id',
            field=models.IntegerField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
