# Generated by Django 4.0.2 on 2022-03-11 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_alter_shoppingcart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='c_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer_Details',
        ),
    ]
