# Generated by Django 4.0.2 on 2022-03-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_shoppingcart_c_id_remove_wishlist_c_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_gateway',
            name='Order_Id',
        ),
    ]
